server:
  port: 8080

spring:
  application:
    name: exchanger


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/exchanger}
    username: ${SPRING_DATASOURCE_USERNAME:exchanger}
    password: ${SPRING_DATASOURCE_PASSWORD:exchanger}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


exchange:
  provider: currencyLayerClient
  api:
    key: ${EXCHANGE_API_KEY}
